apiVersion: v1
kind: ConfigMap
metadata:
  name: mysql-init-configmap
data:
  init.sql: |
    CREATE DATABASE IF NOT EXISTS books;
    USE books;

    CREATE TABLE IF NOT EXISTS books (
        id INT AUTO_INCREMENT PRIMARY KEY,
        title VARCHAR(255) NOT NULL,
        author VARCHAR(255) NOT NULL,
        isbn VARCHAR(20)
    );

    INSERT INTO books (title, author, isbn) VALUES
        ('The Lord of the Rings', 'J.R.R. Tolkien', '978'),
        ('The Hitchhiker\'s Guide to the Galaxy', 'Douglas Adams', '97'),
        ('Pride and Prejudice', 'Jane Austen', '9');
