apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-deployment
spec:
  replicas: 3
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 2
      maxUnavailable: 1
  selector:
    matchLabels:
      app: api
  template:
    metadata:
      labels:
        app: api
    spec:
      containers:
        - name: api
          image: nikhildhawan/my-api-image:latest
          ports:
            - containerPort: 3000
          envFrom:
            - configMapRef:
                name: api-configmap
            - secretRef:
                name: api-secret
          resources:
            requests:
              cpu: "100m"
            limits:
              cpu: "200m"
# Rolling update kubectl set image deployment/api-deployment api=nikhildhawan/my-api-image:v2
